//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTDLEntities : DbContext
    {
        public QLTDLEntities()
            : base("name=QLTDLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTNTQ> CTNTQs { get; set; }
        public virtual DbSet<CTTT> CTTTs { get; set; }
        public virtual DbSet<DOANDL> DOANDLs { get; set; }
        public virtual DbSet<GIATOUR> GIATOURs { get; set; }
        public virtual DbSet<KH> KHs { get; set; }
        public virtual DbSet<LOAITOUR> LOAITOURs { get; set; }
        public virtual DbSet<LOAITT> LOAITTs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NOITHAMQUAN> NOITHAMQUANs { get; set; }
        public virtual DbSet<NVNV> NVNVs { get; set; }
        public virtual DbSet<NVTD> NVTDs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TGTOUR> TGTOURs { get; set; }
        public virtual DbSet<TOUR> TOURs { get; set; }
        public virtual DbSet<TOURDD> TOURDDs { get; set; }
    }
}
