//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGTOUR
    {
        public int ID { get; set; }
        public int IDKH { get; set; }
        public int IDDDL { get; set; }
    
        public virtual DOANDL DOANDL { get; set; }
        public virtual KH KH { get; set; }
    }
}
